version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: prod-pass-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn pass_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/www/pass_manager/staticfiles
      - media_volume:/www/pass_manager/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/www/pass_manager/staticfiles
      - media_volume:/www/pass_manager/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
